spring.application.name=iot-auth-api
server.port=8090

spring.datasource.url=jdbc:mariadb://localhost:3306/iot_room
spring.datasource.username=iot_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false

jwt.secret=REPLACE-THIS-WITH-A-KEY-CONTAINING-AT-LEAST-32-CHARACTERS
jwt.access-token-expiration-ms=86400000
jwt.refresh-token-expiration-ms=2592000000
